### ISSUE TITLE
Dude why did u delete ur https://github.com/ealves-pt/atom-vue2-autocomplete repo?!

### ISSUE THREAD

**Issue by ivan006** [ealves-pt/dotfiles#1]
Dude why did u delete ur https://github.com/ealves-pt/atom-vue2-autocomplete repo?!

I wanted to use that thing :( It had 66k downloads why on earth would u do that?

**Comment by ealves-pt** [comment]
Sorry I honestly didn't know it was still being used since I was not maintaining it for a long time.

Unfortunately, there is no way for me to recover it any longer.

Really sorry for the trouble.
